controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    # Left wheels (Positive Y in your URDF)
    left_wheel_names: ["wheel3_joint", "wheel4_joint"]
    # Right wheels (Negative Y in your URDF)
    right_wheel_names: ["wheel1_joint", "wheel2_joint"]

    wheel_separation: 0.57
    wheel_radius: 0.1

    use_stamped_vel: false  # Important for standard teleop!